services:
    # nginx    
    router:
        image: nginx:latest        
        volumes:
            - ./nginx-default.conf:/etc/nginx/conf.d/default.conf                        
            - ./webapp/public:/var/www/html/public 
            - ./certs/localhost.crt:/etc/nginx/ssl/localhost.crt
            - ./certs/localhost.key:/etc/nginx/ssl/localhost.key  
        ports:
            - "443:443"
    # php
    backend-php-server:
        build:
            dockerfile: ./php/Dockerfile
            target: backend-php-server
        environment:
            LOGGLY_TOKEN: "${LOGGLY_TOKEN}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        extra_hosts:
            - host.docker.internal:host-gateway
    # mysql
    backend-mysql-database:
        image: mysql:latest
        volumes:
            - mysqldata:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d            
        restart: always                    
        command: --init-file /docker-entrypoint-initdb.d/init.sql
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: "${MYSQL_USER}"
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE}"
        ports:
            - "3306"
            
volumes:
    mysqldata: