# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJaneLogInAndOut():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_janeLogInAndOut(self):
    # Test name: janeLogInAndOut
    # Step # | name | target | value
    # 1 | open | /login.php | 
    self.driver.get("https://localhost/login.php")
    # 2 | type | id=username | janedoe
    self.driver.find_element(By.ID, "username").send_keys("janedoe")
    # 3 | type | id=password | Doe12345
    self.driver.find_element(By.ID, "password").send_keys("Doe12345")
    # 4 | waitForElementPresent | xpath=//button[@type='submit'] | 30000
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//button[@type=\'submit\']")))
    # 5 | click | xpath=//button[@type='submit'] | 
    self.driver.find_element(By.XPATH, "//button[@type=\'submit\']").click()
    # 6 | waitForElementPresent | xpath=//a[contains(.,'Welcome janedoe')] | 30000
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//a[contains(.,\'Welcome janedoe\')]")))
    # 7 | click | css=.navbar-toggler-icon | 
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggler-icon").click()
    # 8 | click | xpath=//a[contains(@href, '/logout.php')] | 
    self.driver.find_element(By.XPATH, "//a[contains(@href, \'/logout.php\')]").click()
    # 9 | waitForElementPresent | xpath=//h2[contains(.,'Login')] | 30000
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.XPATH, "//h2[contains(.,\'Login\')]")))
  
