# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestJaneLogIn():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_janeLogIn(self):
    # Test name: janeLogIn
    # Step # | name | target | value
    # 1 | open | /login.php | 
    self.driver.get("https://localhost/login.php")
    # 2 | type | id=username | janedoe
    self.driver.find_element(By.ID, "username").send_keys("janedoe")
    # 3 | type | id=password | Doe12345
    self.driver.find_element(By.ID, "password").send_keys("Doe12345")
    # 4 | click | id=username | 
    self.driver.find_element(By.ID, "username").click()
    # 5 | click | css=.btn-primary | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    # 6 | click | linkText=Welcome janedoe | 
    self.driver.find_element(By.LINK_TEXT, "Welcome janedoe").click()
    # 7 | verifyElementPresent | linkText=Welcome janedoe | 
    elements = self.driver.find_elements(By.LINK_TEXT, "Welcome janedoe")
    assert len(elements) > 0
  
